'use client';
import {useState} from 'react';
import {ArrowLeft,ArrowRight,Plus,Trash2,FileCheck2} from 'lucide-react';
import Link from 'next/link';
import type {CalldataEncodable} from 'genlayer-js/types';
import {artifactKinds,kindLabels,parseGen,formatGen,specificationErrors,type Criterion,type Specification} from '@/lib/domain';
import {useSession} from './session';
type Editable={title:string;amount:string;deadline:string;criteria:Criterion[]};
const emptyCriterion=():Criterion=>({kind:'github_release',source:'',requirement:''});
const defaultDate=()=>new Date(Date.now()+7*86400000).toISOString().slice(0,16);
export function CreateGrant(){
  const {account,connect,run,busy,operation}=useSession();
  const [title,setTitle]=useState(''),[recipient,setRecipient]=useState(''),[budget,setBudget]=useState('3'),[id,setId]=useState(''),[error,setError]=useState(''),[attempted,setAttempted]=useState(false);
  const [milestones,setMilestones]=useState<Editable[]>([{title:'',amount:'3',deadline:'',criteria:[emptyCriterion()]}]);
  const update=(index:number,change:Partial<Editable>)=>setMilestones(previous=>previous.map((m,i)=>i===index?{...m,...change}:m));
  function specification():Specification{return {title,recipient:recipient.toLowerCase(),budget:parseGen(budget).toString(),milestones:milestones.map(m=>({title:m.title,allocation:parseGen(m.amount).toString(),deadline:Math.floor(new Date(m.deadline+'Z').getTime()/1000),criteria:m.criteria}))};}
  let allocation='—',errors:string[]=[];
  try{const allocated=milestones.reduce((sum,m)=>sum+parseGen(m.amount),0n);allocation=formatGen(allocated);errors=specificationErrors(specification());}catch(e){errors=[e instanceof Error?e.message:'Check amounts and deadlines.'];}
  const matched=(()=>{try{return milestones.reduce((sum,m)=>sum+parseGen(m.amount),0n)===parseGen(budget);}catch{return false;}})();
  async function submit(event:React.FormEvent){event.preventDefault();setAttempted(true);setError('');if(errors.length)return;try{if(!account){await connect();return;}const spec=specification();const identifier=id||'grant-'+crypto.randomUUID().slice(0,18);setId(identifier);const steps:{method:string;args:CalldataEncodable[]}[]=[{method:'propose',args:[identifier,JSON.stringify(spec)]}];spec.milestones.forEach((m,i)=>m.criteria.forEach((_,j)=>steps.push({method:'check_spec',args:[identifier,i,j]})));await run('Validate grant criteria',identifier,steps);}catch(e){setError(e instanceof Error?e.message:'Grant creation failed.');}}
  const submitted=operation?.grantId===id&&!!id;
  return <div id="content"><Link href="/" className="back-link"><ArrowLeft size={15}/>Grant ledger</Link><div className="page-intro"><h1>Put the work in writing.</h1><p>Define what ships. Fix what it earns. Validators check that each clause can be verified before any money is escrowed.</p></div><div className="agreement-layout"><form onSubmit={submit} className="create-form"><section className="form-section"><h2>The agreement</h2><label>Grant title<input value={title} onChange={e=>setTitle(e.target.value)} maxLength={120} placeholder="e.g. Open-source wallet integration" required/></label><label>Recipient wallet<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="0x…" spellCheck={false} required/><span className="field-note">Only this address can submit milestone evidence.</span></label><label>Total budget <span className="unit">GEN</span><input inputMode="decimal" value={budget} onChange={e=>setBudget(e.target.value)} required/><span className="field-note">StudioNet GEN is simulated development value.</span></label></section>
    {milestones.map((m,index)=><section className="form-section" key={index}><div className="section-heading"><h2>Milestone {index+1}</h2>{milestones.length>1&&<button type="button" className="text-button" aria-label={`Remove milestone ${index+1}`} onClick={()=>setMilestones(previous=>previous.filter((_,i)=>i!==index))}><Trash2 size={15}/>Remove</button>}</div><label>Milestone title<input value={m.title} onChange={e=>update(index,{title:e.target.value})} maxLength={120} placeholder="Name a concrete delivery" required/></label><div className="field-row"><label>Allocation · GEN<input inputMode="decimal" value={m.amount} onChange={e=>update(index,{amount:e.target.value})} required/></label><label>Deadline · UTC<input type="datetime-local" value={m.deadline} onChange={e=>update(index,{deadline:e.target.value})} required/></label></div>{!m.deadline&&<button type="button" className="text-button" onClick={()=>update(index,{deadline:defaultDate()})}>Set deadline to one week from now</button>}
      <h3>Acceptance criteria</h3><p className="muted small">One public artifact and one observable property per clause.</p>{m.criteria.map((c,j)=><div className="criterion-form" key={j}><div className="section-heading"><strong>Clause {j+1}</strong>{m.criteria.length>1&&<button type="button" className="text-button" aria-label={`Remove criterion ${j+1} from milestone ${index+1}`} onClick={()=>update(index,{criteria:m.criteria.filter((_,k)=>j!==k)})}><Trash2 size={14}/></button>}</div><label>Artifact type<select value={c.kind} onChange={e=>update(index,{criteria:m.criteria.map((v,k)=>j===k?{...v,kind:e.target.value as Criterion['kind'],source:''}:v)})}>{artifactKinds.map(kind=><option value={kind} key={kind}>{kindLabels[kind]}</option>)}</select></label><label>{c.kind.startsWith('github_')?'GitHub repository':c.kind==='npm_version'?'npm package':c.kind==='archive_snapshot'?'Original public URL':'Contract address'}<input value={c.source} onChange={e=>update(index,{criteria:m.criteria.map((v,k)=>j===k?{...v,source:e.target.value}:v)})} placeholder={c.kind.startsWith('github_')?'owner/repository':c.kind==='npm_version'?'package-name':c.kind==='archive_snapshot'?'https://example.com/page':'0x…'} required spellCheck={false}/></label><label>Expected property<textarea value={c.requirement} onChange={e=>update(index,{criteria:m.criteria.map((v,k)=>j===k?{...v,requirement:e.target.value}:v)})} placeholder="e.g. The repository’s release notes announce wallet connection support." rows={3} maxLength={1000} required/></label></div>)}{m.criteria.length<5&&<button type="button" className="text-button" onClick={()=>update(index,{criteria:[...m.criteria,emptyCriterion()]})}><Plus size={14}/>Add criterion</button>}</section>)}
    {milestones.length<3&&<button type="button" className="button add-milestone" onClick={()=>setMilestones(previous=>[...previous,{title:'',amount:'1',deadline:'',criteria:[emptyCriterion()]}])}><Plus size={16}/>Add milestone</button>}
    <div className={'allocation-check '+(matched?'valid':'invalid')}><FileCheck2 size={18}/><span>{allocation} of {budget||'0'} GEN allocated</span><strong>{matched?'Balanced':'Allocations must match'}</strong></div>{attempted&&errors.length>0&&<ul className="notice error" role="alert">{errors.map(e=><li key={e}>{e}</li>)}</ul>}{error&&<p className="notice error" role="alert">{error}</p>}
    <button className="button primary submit-button" disabled={busy||submitted}>{busy?'Checking criteria…':account?'Validate criteria':'Connect wallet to continue'}<ArrowRight size={16}/></button>{submitted&&<Link href={'/grants/'+id} className="button">Inspect specification result <ArrowRight size={16}/></Link>}
  </form><aside className="agreement-sidebar"><div className="side-section"><h2>Before you fund</h2><ol className="process-list"><li><strong>Write verifiable clauses</strong><p>Public source, fixed allocation, concrete property.</p></li><li><strong>Let validators check</strong><p>Each criterion gets its own judgment. Rejections include a reason.</p></li><li><strong>Freeze and escrow</strong><p>After SPEC_ACCEPTED finalizes, you sign the exact budget deposit.</p></li></ol></div><div className="side-section"><h3>Good clauses name facts.</h3><p>“Release notes announce wallet connection” is observable. “Make a high-quality interface” is not.</p><p className="muted">Criteria and allocations cannot be edited after proposal. Revise a rejected agreement by creating a new grant.</p></div></aside></div></div>;
}
