'use client';
import {useCallback,useEffect,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {ArrowUpRight,Check,ChevronDown,Clock3,ExternalLink,FileText,LockKeyhole,RefreshCw,ShieldCheck,ArrowRight} from 'lucide-react';
import {explorer,formatGen,shortAddress,kindLabels,evidenceFor,fetchTargets,type Proof,type Grant,type Criterion,type Evidence,type Milestone} from '@/lib/domain';
import {useSession} from './session';

const date=(time:number)=>new Date(time*1000).toLocaleString('en-GB',{dateStyle:'medium',timeStyle:'short',timeZone:'UTC'})+' UTC';
function useClock(){const [time,setTime]=useState<number|null>(null);useEffect(()=>{const tick=()=>setTime(Date.now()/1000);const timer=setInterval(tick,1000);return()=>clearInterval(timer);},[]);return time;}
function Status({status}:{status:string}){const met=status==='MET',held=status==='NOT_MET'||status==='INSUFFICIENT_EVIDENCE';return <span className={'status '+(met?'met':held?'held':status==='REFUNDED'?'refunded':'neutral')}>{met?<Check size={13}/>:held?<LockKeyhole size={12}/>:<Clock3 size={12}/>}<span>{met?'MET · Released':status==='NOT_MET'?'NOT MET · Held':status==='INSUFFICIENT_EVIDENCE'?'INSUFFICIENT EVIDENCE · Held':status.replaceAll('_',' ')}</span></span>;}

export function GrantView({proof,grantId}:{proof:Proof;grantId?:string}){
  const identifier=grantId??proof.grantId??'',isSeed=identifier===proof.grantId;
  const [record,setRecord]=useState<Grant|null>(isSeed?proof.record??null:null),[readAt,setReadAt]=useState(''),[source,setSource]=useState<'recorded'|'live'>(isSeed?'recorded':'live'),[reading,setReading]=useState(false),[error,setError]=useState(''),[lookup,setLookup]=useState('');
  const {account,busy,run,connect,operation}=useSession();
  const time=useClock(),router=useRouter();
  const refresh=useCallback(async()=>{if(!identifier)return;setReading(true);setError('');try{const response=await fetch('/api/grant?id='+encodeURIComponent(identifier),{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error);setRecord(result.record);setReadAt(result.readAt);setSource('live');}catch(e){setError(e instanceof Error?e.message:'Could not read this grant.');}finally{setReading(false);}},[identifier]);
  useEffect(()=>{if(!isSeed)void Promise.resolve().then(refresh);window.addEventListener('tranche:updated',refresh);return()=>window.removeEventListener('tranche:updated',refresh);},[isSeed,refresh]);
  useEffect(()=>{if(!busy||operation?.grantId!==identifier)return;const timer=setInterval(()=>void refresh(),30000);return()=>clearInterval(timer);},[busy,operation?.grantId,identifier,refresh]);
  async function act(label:string,method:string,value?:string){setError('');try{if(!account){await connect();return;}await run(label,identifier,[{method,args:[identifier],value}]);await refresh();}catch(e){setError(e instanceof Error?e.message:'The action could not complete.');}}
  const funder=account===record?.funder,recipient=account===record?.spec.recipient;
  return <div id="content"><div className="ledger-path"><Link href="/">Grant ledger</Link><span>/</span><span>{identifier||'Demonstration'}</span><span className="network-label"><span className="network-dot"/>StudioNet</span></div>
    {!record?<section className="empty-state"><FileText size={35}/><h1>{reading?'Reading the agreement…':isSeed?'The live demonstration is being recorded.':'Open a grant agreement.'}</h1><p>{error||'Every outcome shown here must come from a finalized, successful transaction.'}</p><button className="button" onClick={()=>void refresh()} disabled={reading}>Read finalized state <RefreshCw size={15}/></button></section>:<>
    <div className="grant-heading"><div><h1>{isSeed?'Money follows\nshipped work.':record.spec.title}</h1><p>{isSeed?'A real public release. Three frozen clauses. Three independently verified outcomes.':record.spec.title}</p></div><div className="agreement-seal"><ShieldCheck size={24} strokeWidth={1.4}/><span>Criteria frozen</span><small>SHA-256 agreement</small></div></div>
    <section className="grant-summary" aria-label="Grant amounts"><div className="summary-title"><span>{record.spec.title}</span><span className="grant-status">{record.status==='OPEN'?'Funded agreement':record.status.replaceAll('_',' ')}</span></div><div className="summary-amounts"><div><span>Total budget</span><strong>{formatGen(record.spec.budget)} <small>GEN</small></strong></div><div><span>Released</span><strong className="green">{formatGen(record.released)} <small>GEN</small></strong></div><div><span>Held in escrow</span><strong>{formatGen(record.held??'0')} <small>GEN</small></strong></div>{BigInt(record.refunded)>0n&&<div><span>Refunded</span><strong>{formatGen(record.refunded)} <small>GEN</small></strong></div>}</div><div className="allocation-bar" aria-label="Milestone allocations">{record.milestones.map((m,i)=><div className={'allocation-segment '+(m.status==='MET'?'released':m.status==='REFUNDED'?'returned':'remaining')} style={{flex:Number(BigInt(m.allocation)*10000n/BigInt(record.spec.budget))}} key={i}><span>Milestone {i+1}</span><span>{formatGen(m.allocation)} GEN</span></div>)}</div></section>
    <p className="settlement-rule"><strong>All criteria met: release the fixed allocation.</strong> A criterion not met or missing evidence keeps the money held.</p>
    <div className="proof-source"><div>{source==='recorded'?<FileText size={15}/>:<RefreshCw size={15}/>}<span><strong>{source==='recorded'?'Recorded execution proof':'Live finalized chain state'}</strong>{source==='recorded'?' · captured '+(proof.recordedAt?new Date(proof.recordedAt).toLocaleDateString('en-GB',{timeZone:'UTC'}):'during deployment'):' · '+new Date(readAt).toLocaleTimeString('en-GB',{timeZone:'UTC'})+' UTC'}</span></div><button className="text-button" onClick={()=>void refresh()} disabled={reading}><RefreshCw size={13} className={reading?'spin':''}/>{reading?'Reading…':'Read live state'}</button></div>
    {error&&<p className="notice error" role="alert">{error}</p>}
    <div className="agreement-layout"><section className="milestone-list" aria-label="Milestone clauses"><div className="section-heading"><h2>The milestones</h2><span className="muted small">{record.milestones.length} clauses · fixed allocations</span></div>{record.milestones.map((m,index)=><MilestoneClause milestone={m} index={index} grant={record} proof={isSeed?proof:undefined} key={index} refresh={refresh} recipient={recipient}/>)}
    {record.status==='SPEC_REJECTED'&&<div className="notice error"><h3>Specification rejected</h3><p>The agreement cannot be funded. Review each criterion’s rejection reason, then create a revised grant.</p><Link href="/create">Write a new agreement <ArrowRight size={14}/></Link></div>}</section>
    <aside className="agreement-sidebar"><div className="side-section"><h2>Agreement terms</h2><dl><div><dt>Funder</dt><dd><a href={`${explorer}/address/${record.funder}`} target="_blank" rel="noreferrer">{shortAddress(record.funder)}<ArrowUpRight size={13}/></a></dd></div><div><dt>Recipient</dt><dd><a href={`${explorer}/address/${record.spec.recipient}`} target="_blank" rel="noreferrer">{shortAddress(record.spec.recipient)}<ArrowUpRight size={13}/></a></dd></div><div><dt>Final deadline</dt><dd>{date(Math.max(...record.milestones.map(m=>m.deadline)))}</dd></div><div><dt>Resubmission</dt><dd>Once per held milestone</dd></div><div><dt>Appeals</dt><dd>Native GenLayer window</dd></div></dl><details className="hash-details"><summary><LockKeyhole size={13}/>Frozen agreement hash</summary><code>{record.spec_hash}</code></details></div>
    <div className="side-section"><h3>Settlement is in the code.</h3><p>All criteria met: release the fixed allocation. Any criterion not met: hold. Missing evidence: hold.</p><p className="muted">Only finalized judgments can settle. In-flight claims have a one-hour grace period after their deadline.</p>{record.status==='SPEC_ACCEPTED'&&<><p>Criteria accepted. Deposit exactly {formatGen(record.spec.budget)} GEN to open this agreement.</p><button className="button primary" onClick={()=>void act('Fund the grant','fund',record.spec.budget)} disabled={busy||!!account&&!funder}>{account?'Fund agreement':'Connect as funder'}</button></>}{record.status==='OPEN'&&BigInt(record.held)>0n&&<button className="button" onClick={()=>void act('Refund expired allocations','refund')} disabled={busy||time===null||time<=Math.max(...record.milestones.map(m=>m.deadline))}>Refund after final deadline</button>}</div>
    <div className="side-section protocol-links"><a href={`${explorer}/address/${proof.contract}`} target="_blank" rel="noreferrer">Escrow contract <ArrowUpRight size={14}/></a><Link href="/proof">Execution receipts <ArrowUpRight size={14}/></Link><a href="https://docs.genlayer.com/understand-genlayer-protocol/core-concepts/optimistic-democracy/appeals" target="_blank" rel="noreferrer">How native appeals work <ArrowUpRight size={14}/></a><p className="small muted">Balances above are {source==='live'?'read from finalized chain state':'part of the recorded proof'}. Released allocations and credited native transfers have separate receipts.</p></div></aside></div></>}
    <form className="lookup" onSubmit={e=>{e.preventDefault();if(/^[a-z0-9-]{3,64}$/.test(lookup))router.push('/grants/'+lookup);}}><label htmlFor="grant-lookup">Have another grant?</label><div><input id="grant-lookup" value={lookup} onChange={e=>setLookup(e.target.value)} placeholder="Enter its grant ID" pattern="[a-z0-9-]{3,64}" required/><button className="button" type="submit">Open grant <ArrowRight size={14}/></button></div></form>
  </div>;
}

function MilestoneClause({milestone:m,index,grant,proof,refresh,recipient}:{milestone:Milestone;index:number;grant:Grant;proof?:Proof;refresh:()=>Promise<void>;recipient:boolean}){
  const [attaching,setAttaching]=useState(false),{account,connect,run,busy}=useSession(),[error,setError]=useState('');
  const time=useClock();
  const held=m.status==='NOT_MET'||m.status==='INSUFFICIENT_EVIDENCE';
  const claimable=grant.status==='OPEN'&&['UNCLAIMED','NOT_MET','INSUFFICIENT_EVIDENCE'].includes(m.status)&&m.attempt<2&&time!==null&&time<m.deadline;
  async function judge(){setError('');try{if(!account){await connect();return;}const steps=m.criteria.flatMap((_,j)=>m.judgments[j]===null?[{method:'adjudicate',args:[grant.id,index,j]}]:[]);await run('Judge milestone '+(index+1),grant.id,steps);await refresh();}catch(e){setError(e instanceof Error?e.message:'Judgment could not start.');}}
  return <article className="milestone-clause"><div className="clause-top"><span className="clause-number">{String(index+1).padStart(2,'0')}</span><div className="clause-title"><h3>{m.title}</h3><span className="clause-date"><Clock3 size={12}/>{date(m.deadline)}</span></div><strong className="clause-allocation">{formatGen(m.allocation)} <small>GEN</small></strong></div><div className="clause-status"><Status status={m.status}/><span className="muted small">{m.judgments.filter(j=>j?.finalized).length}/{m.criteria.length} criteria finalized</span></div><details className="clause-details" open={index===0}><summary>Inspect criteria &amp; evidence <ChevronDown size={15}/></summary><div className="clause-body">{m.criteria.map((c,j)=>{const judgment=m.judgments[j],evidence=m.evidence[j],check=m.spec_checks[j];return <div className="criterion-result" key={j}><div className="criterion-label"><span>{kindLabels[c.kind]} · {c.source}</span>{judgment&&<span className={'verdict '+(judgment.verdict==='MET'?'green':'')}>{judgment.verdict.replaceAll('_',' ')}</span>}</div><p className="criterion-text">{c.requirement}</p>{check&&!check.accepted&&<p className="notice error">Criteria rejected: {check.reason} {check.finalized?'(finalized)':'(awaiting finality)'}</p>}{judgment?.quote?<blockquote><span className="quote-mark">“</span>{judgment.quote}<span className="quote-mark">”</span></blockquote>:judgment&&<p className="missing-evidence">No verified passage available. The artifact could not be fetched at this reference.</p>}{judgment&&<p className="judgment-reason">{judgment.reason}</p>}{evidence&&<div className="evidence-links"><a href={evidence.url} target="_blank" rel="noreferrer">Open public artifact <ExternalLink size={12}/></a>{evidence.sha&&<a href={`https://github.com/${c.source}/commit/${evidence.sha}`} target="_blank" rel="noreferrer">Pinned commit {evidence.sha.slice(0,8)}<ArrowUpRight size={12}/></a>}</div>}</div>;})}
    {m.history.length>0&&<details><summary>Previous claim · {m.history[0].status.replaceAll('_',' ')}</summary>{m.history.map(h=><div key={h.attempt}><p>Attempt {h.attempt}: {h.status}</p>{h.judgments.map((j,k)=>j&&<p key={k}>{j.verdict}: {j.quote||j.reason}</p>)}</div>)}</details>}
    {proof?.transactions['demo-judge-'+index]&&<div className="clause-receipt"><ShieldCheck size={14}/><span>Judgment finalized</span><a href={`${explorer}/transactions/${proof.transactions['demo-judge-'+index]}`} target="_blank" rel="noreferrer">View transaction <ArrowUpRight size={12}/></a></div>}</div></details>
    {held&&<div className="hold-note">{m.attempt<2?'Allocation held. One resubmission is available before the deadline.':'Allocation held. The single resubmission has been used.'}</div>}
    {claimable&&<div className="clause-actions"><button className="button" onClick={()=>setAttaching(v=>!v)} disabled={busy}>{held?'Resubmit evidence':'Attach evidence'}<ArrowRight size={14}/></button><span className="muted small">{recipient?'Your recipient wallet is connected.':'The recipient signs the claim.'}</span></div>}
    {attaching&&claimable&&<ClaimForm grant={grant} index={index} close={()=>setAttaching(false)} refresh={refresh}/>}
    {m.status==='JUDGING'&&<div className="clause-actions"><button className="button primary" disabled={busy||!m.judgments.some(j=>j===null)} onClick={()=>void judge()}>Judge remaining criteria</button><p className="muted small">Anyone can request judgment for the recipient’s finalized claim.</p></div>}{error&&<p role="alert" className="notice error">{error}</p>}
  </article>;
}

function ClaimForm({grant,index,close,refresh}:{grant:Grant;index:number;close:()=>void;refresh:()=>Promise<void>}){
  const m=grant.milestones[index],{run,busy,account,connect}=useSession();
  const [fields,setFields]=useState<Record<string,string>[]>(m.criteria.map(()=>({}))),[preview,setPreview]=useState<{criterion:Criterion;evidence:Evidence;targets:string[];body?:string;error?:string}[]|null>(null),[error,setError]=useState(''),[previewing,setPreviewing]=useState(false);
  const update=(i:number,key:string,value:string)=>{setFields(previous=>previous.map((f,j)=>j===i?{...f,[key]:value}:f));setPreview(null);};
  function refs(){return m.criteria.map((c,i)=>evidenceFor(c,fields[i]));}
  async function preflight(){setError('');setPreviewing(true);try{const evidence=refs();const previews=[];for(let i=0;i<evidence.length;i++){const targets=fetchTargets(m.criteria[i],evidence[i]);const response=await fetch('/api/preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({criterion:m.criteria[i],evidence:evidence[i]})});const result=await response.json();previews.push({criterion:m.criteria[i],evidence:evidence[i],targets,body:result.body,error:result.error});}setPreview(previews);}catch(e){setError(e instanceof Error?e.message:'Check the evidence reference.');}finally{setPreviewing(false);}}
  async function submit(e:React.FormEvent){e.preventDefault();setError('');try{if(!preview)throw Error('Preview the fetched evidence before signing the claim.');if(!account){await connect();return;}if(account!==grant.spec.recipient)throw Error('Connect the named recipient wallet to claim this milestone.');const evidence=refs();await run('Claim and judge milestone '+(index+1),grant.id,[{method:'claim',args:[grant.id,index,JSON.stringify(evidence)]},...m.criteria.map((_,j)=>({method:'adjudicate',args:[grant.id,index,j]}))]);await refresh();close();}catch(err){setError(err instanceof Error?err.message:'Claim could not be submitted.');}}
  return <form onSubmit={submit} className="claim-form"><h4>Evidence for this milestone</h4>{m.criteria.map((c,i)=><fieldset key={i}><legend>{kindLabels[c.kind]} · clause {i+1}</legend>{c.kind==='github_release'||c.kind==='github_tag'?<label>Exact release / tag<input value={fields[i].tag??''} onChange={e=>update(i,'tag',e.target.value)} placeholder="v1.0.0" required/></label>:null}{c.kind.startsWith('github_')&&<label>Pinned commit SHA<input value={fields[i].sha??''} onChange={e=>update(i,'sha',e.target.value)} placeholder="40 lowercase hexadecimal characters" spellCheck={false} required/></label>}{c.kind==='github_file'&&<label>File path<input value={fields[i].path??''} onChange={e=>update(i,'path',e.target.value)} placeholder="src/wallet.ts" required/></label>}{c.kind==='npm_version'&&<label>Package version<input value={fields[i].version??''} onChange={e=>update(i,'version',e.target.value)} placeholder="1.0.0" required/></label>}{c.kind==='archive_snapshot'&&<label>Archive timestamp · UTC<input value={fields[i].capture??''} onChange={e=>update(i,'capture',e.target.value)} placeholder="20261005120000" required/></label>}</fieldset>)}<button type="button" className="button" disabled={previewing||busy} onClick={()=>void preflight()}>{previewing?'Fetching preview…':'Preview validator fetch'}<ExternalLink size={14}/></button>{preview&&<div className="preflight"><h4>What validators will fetch</h4><p className="muted small">Convenience preview only. Validators fetch independently and decide on-chain.</p>{preview.map((p,i)=><div key={i}>{p.targets.map(url=><a href={url} key={url} target="_blank" rel="noreferrer">{url}<ArrowUpRight size={12}/></a>)}{p.body?<pre>{p.body}</pre>:<p>{p.error||'No preview body is available. Unreachable artifacts may be held for insufficient evidence.'}</p>}</div>)}</div>}{error&&<p className="notice error" role="alert">{error}</p>}<div className="clause-actions"><button type="submit" className="button primary" disabled={busy||!preview}>{account?'Sign claim and request judgment':'Connect recipient wallet'}<ArrowRight size={14}/></button><button type="button" className="text-button" onClick={close}>Cancel</button></div></form>;
}
